name: christopherwiitala
favicon: null
layout_spectrum: 0.2566
typography_spectrum: 0.52634
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-21311057-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#b1ca01'
    - '#dff926'
    - '#524d39'
    - '#239c07'
  brandStrength: 0
  lightness: 0
  saturation: 0.0625
  rhythmicContrast: 0
purpose: []
