name: christopher wiitala
favicon: null
layout_spectrum: 0
typography_spectrum: 0.52634
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-21311057-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#050505'
    - '#264758'
    - '#3e5a68'
    - '#734c3d'
    - '#232726'
  brandStrength: 0
  lightness: 1
  saturation: 0
  rhythmicContrast: 0
purpose: []
