name: christopher wiitala
favicon: null
layout_spectrum: 0.24277
typography_spectrum: 0.52634
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-21311057-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#96b4e8'
    - '#4c7fd8'
    - '#d39a49'
    - '#52373b'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 0
purpose: []
